   version: '3'

   services:
     devpi:
       image: muccg/devpi
       ports:
         - 127.0.0.1:3141:3141
       volumes:
         - devpi-data:/root/.devpi

   volumes:
     devpi-data:
        driver: local
        name: devpi-data
